_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 55
                - 105
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
                - 80
                - 105
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.10
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
autoencoder:
    value:
        ckpt_path: weights/autoencoder_vq_f4.pth
        params:
            ddconfig:
                attn_resolutions: []
                ch: 128
                ch_mult:
                    - 1
                    - 2
                    - 4
                double_z: false
                dropout: 0
                in_channels: 3
                num_res_blocks: 2
                out_ch: 3
                padding_mode: zeros
                resolution: 256
                z_channels: 3
            embed_dim: 3
            lora_tune_decoder: false
            n_embed: 8192
        target: ldm.models.autoencoder.VQModelTorch
        tune_decoder: false
        use_fp16: true
cfg_path:
    value: configs/realsr_swinunet_realesrgan256.yaml
data:
    value:
        train:
            params:
                opt:
                    dataroot_gt: ../ChestCT/HR
                    dataroot_lq: ../ChestCT/LR
                    dataroot_mask: ../ChestCT/mask
                    gt_size: 256
                    io_backend:
                        type: disk
                    meta_info_file: data/meta_info/meta_info_ChestCT_val_2715_part_60.txt
                    phase: train
                    scale: 4
                    use_hflip: true
                    use_rot: true
            type: PairedImageDataset
        val:
            params:
                opt:
                    dataroot_gt: ../ChestCT/HR
                    dataroot_lq: ../ChestCT/LR
                    dataroot_mask: ../ChestCT/mask
                    io_backend:
                        type: disk
                    meta_info_file: data/meta_info/meta_info_ChestCT_val_2715_part_60.txt
                    phase: val
                    scale: 4
            type: PairedImageDataset
degradation:
    value:
        gaussian_noise_prob: 0.5
        gaussian_noise_prob2: 0.5
        gray_noise_prob: 0.4
        gray_noise_prob2: 0.4
        gt_size: 256
        jpeg_range:
            - 30
            - 95
        jpeg_range2:
            - 30
            - 95
        noise_range:
            - 1
            - 30
        noise_range2:
            - 1
            - 25
        poisson_scale_range:
            - 0.05
            - 3
        poisson_scale_range2:
            - 0.05
            - 2.5
        resize_back: false
        resize_prob:
            - 0.2
            - 0.7
            - 0.1
        resize_prob2:
            - 0.3
            - 0.4
            - 0.3
        resize_range:
            - 0.15
            - 1.5
        resize_range2:
            - 0.3
            - 1.2
        second_blur_prob: 0.8
        second_order_prob: 0.5
        sf: 4
        use_sharp: false
diffusion:
    value:
        params:
            etas_end: 0.99
            kappa: 2
            latent_flag: true
            min_noise_level: 0.04
            normalize_input: true
            predict_type: xstart
            scale_factor: 1
            schedule_kwargs:
                power: 0.3
            schedule_name: exponential
            sf: 4
            steps: 15
            timestep_respacing: null
            weighted_mse: false
        target: models.script_util.create_gaussian_diffusion
logger:
    value:
        wandb:
            id: null
            name: ronbunnomama
            project: experiment5
model:
    value:
        ckpt_path: null
        params:
            attention_resolutions:
                - 64
                - 32
                - 16
                - 8
            channel_mult:
                - 1
                - 2
                - 2
                - 4
            cond_lq: true
            conv_resample: true
            dims: 2
            dropout: 0
            image_size: 64
            in_channels: 3
            lq_size: 64
            mlp_ratio: 4
            model_channels: 160
            num_head_channels: 32
            num_res_blocks:
                - 2
                - 2
                - 2
                - 2
            out_channels: 3
            resblock_updown: false
            swin_depth: 2
            swin_embed_dim: 192
            use_fp16: false
            use_scale_shift_norm: true
            window_size: 8
        target: models.unet.UNetModelSwin
resume:
    value: ""
save_dir:
    value: results
train:
    value:
        batch:
            - 8
            - 1
        compile:
            flag: false
            mode: reduce-overhead
        ema_rate: 0.999
        global_seeding: false
        iterations: 300000
        local_logging: true
        log_freq:
            - 200
            - 2000
            - 1
        lr: 5e-05
        lr_min: 2e-05
        lr_schedule: null
        microbatch: 8
        num_workers: 4
        prefetch_factor: 2
        save_freq: 10000
        scale: 4
        seed: 123456
        tf_logging: false
        use_amp: true
        use_ema_val: true
        val_freq: 100
        val_padding_mode: reflect
        val_resolution: 64
        val_y_channel: true
        warmup_iterations: 5000
        weight_decay: 0
trainer:
    value:
        target: trainer.TrainerDifIR
